apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-prd.yml
    kompose.service.type: LoadBalancer
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: mongo-tcp
  name: mongo-tcp
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo
  type: LoadBalancer
